### PR TITLE
sets WM_NAME to "slock"

### PR DESCRIPTION
**Pull request by ghost**
useful when a compositor is running (e.g. compton) with inactive window
transparency enabled, just write a focus-exclude rule as:
`focus-exclude = [ "name = 'slock'" ];`

### CODE REVIEW

**Comment by MightyPork** [comment]
why not, looks useful. thanks

**Comment by ghost** [comment]
I really need this feature, thank you for your work

**Comment by MightyPork** [comment]
no problem. should be now also in AUR (slock-xtra-git)

**Comment by ghost** [comment]
Ok.

I made some mistake earlier with the pull request. It's my first one and I
was convinced that it would point to the head of my master branch at the
time of the pull request. So I was trying to change the pkgbuild
accordingly to my changes.

**Comment by MightyPork** [comment]
sorry I don't understand. Was the code you added not OK?

**Comment by ghost** [comment]
Yes it is! Don't mind.

Ps. The aur description says "wm_class", it's wm_name actually

**Comment by MightyPork** [comment]
thanks, fixed.

**Pull request merged**
